/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Badge {
  'id' : string,
  'badgeType' : BadgeType,
  'name' : string,
  'description' : string,
  'earnedAt' : Timestamp,
}
export type BadgeType = { 'Gifter' : null } |
  { 'MegaWinner' : null } |
  { 'Participant' : null } |
  { 'Winner' : null };
export type ClaimStatus = { 'Processing' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface Draw {
  'id' : DrawId,
  'status' : DrawStatus,
  'drawnNumbers' : Array<bigint>,
  'fairnessSeal' : string,
  'lotteryId' : LotteryId,
  'drawnAt' : [] | [Timestamp],
}
export type DrawId = string;
export type DrawStatus = { 'InProgress' : null } |
  { 'Completed' : null } |
  { 'Upcoming' : null };
export interface Lottery {
  'id' : LotteryId,
  'lotteryType' : LotteryType,
  'name' : string,
  'drawDate' : Timestamp,
  'isActive' : boolean,
  'participatingCountries' : Array<string>,
  'ticketPrice' : bigint,
  'prizePool' : bigint,
}
export type LotteryId = string;
export type LotteryType = { 'NoLoss' : null } |
  { 'Classic645' : null } |
  { 'Daily' : null } |
  { 'NFTRaffle' : null };
export interface POSSale {
  'id' : string,
  'soldAt' : Timestamp,
  'storeId' : StoreId,
  'ticketIds' : Array<TicketId>,
  'commission' : bigint,
  'totalAmount' : bigint,
}
export type PayoutMethod = { 'BankTransfer' : null } |
  { 'Crypto' : null } |
  { 'Wallet' : null } |
  { 'StoreCredit' : null };
export interface PrizeClaim {
  'id' : string,
  'status' : ClaimStatus,
  'method' : PayoutMethod,
  'userId' : UserId,
  'ticketId' : TicketId,
  'claimedAt' : Timestamp,
  'amountClaimed' : bigint,
}
export interface Store {
  'id' : StoreId,
  'lat' : number,
  'lng' : number,
  'country' : string,
  'city' : string,
  'name' : string,
  'hoursOpen' : string,
  'address' : string,
  'hasTickets' : boolean,
  'phone' : [] | [string],
}
export type StoreId = string;
export interface Ticket {
  'id' : TicketId,
  'status' : TicketStatus,
  'ownerId' : UserId,
  'isGifted' : boolean,
  'artSeed' : bigint,
  'lotteryId' : LotteryId,
  'purchasedAt' : Timestamp,
  'numbers' : Array<bigint>,
  'giftedTo' : [] | [string],
}
export type TicketId = string;
export type TicketStatus = { 'Unclaimed' : null } |
  { 'Lost' : null } |
  { 'Active' : null } |
  { 'Winner' : null } |
  { 'InDraw' : null };
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserPublic {
  'id' : UserId,
  'country' : string,
  'isGuest' : boolean,
  'name' : string,
  'joinedAt' : Timestamp,
  'email' : [] | [string],
  'currency' : string,
}
export interface UserSettings {
  'notificationsEnabled' : boolean,
  'country' : string,
  'language' : string,
  'currency' : string,
}
export interface UserStats {
  'badges' : Array<string>,
  'totalWins' : bigint,
  'totalWon' : bigint,
  'totalSpent' : bigint,
  'totalTickets' : bigint,
}
export interface Winner {
  'id' : string,
  'lotteryName' : string,
  'country' : string,
  'consentToShare' : boolean,
  'displayName' : string,
  'prizeAmount' : bigint,
  'userId' : UserId,
  'wonAt' : Timestamp,
}
export interface _SERVICE {
  'claimPrize' : ActorMethod<[TicketId, PayoutMethod], [] | [PrizeClaim]>,
  'createUser' : ActorMethod<
    [string, [] | [string], string, string, boolean],
    UserPublic
  >,
  'getDrawByLottery' : ActorMethod<[LotteryId], Array<Draw>>,
  'getLatestDraw' : ActorMethod<[LotteryId], [] | [Draw]>,
  'getLotteries' : ActorMethod<[], Array<Lottery>>,
  'getLotteryById' : ActorMethod<[LotteryId], [] | [Lottery]>,
  'getMyBadges' : ActorMethod<[], Array<Badge>>,
  'getMyTickets' : ActorMethod<[], Array<Ticket>>,
  'getStoreSales' : ActorMethod<[StoreId], Array<POSSale>>,
  'getStores' : ActorMethod<[], Array<Store>>,
  'getStoresByCountry' : ActorMethod<[string], Array<Store>>,
  'getTicketById' : ActorMethod<[TicketId], [] | [Ticket]>,
  'getUser' : ActorMethod<[UserId], [] | [UserPublic]>,
  'getUserStats' : ActorMethod<[], [] | [UserStats]>,
  'getWinners' : ActorMethod<[], Array<Winner>>,
  'giftTicket' : ActorMethod<[TicketId, string], boolean>,
  'purchaseTicket' : ActorMethod<[LotteryId, Array<bigint>, bigint], Ticket>,
  'recordSale' : ActorMethod<
    [StoreId, Array<TicketId>, bigint, bigint],
    POSSale
  >,
  'updateSettings' : ActorMethod<[UserSettings], boolean>,
  'updateUserProfile' : ActorMethod<
    [[] | [string], [] | [string], [] | [string], [] | [string]],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];