/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TicketId = IDL.Text;
export const PayoutMethod = IDL.Variant({
  'BankTransfer' : IDL.Null,
  'Crypto' : IDL.Null,
  'Wallet' : IDL.Null,
  'StoreCredit' : IDL.Null,
});
export const ClaimStatus = IDL.Variant({
  'Processing' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const PrizeClaim = IDL.Record({
  'id' : IDL.Text,
  'status' : ClaimStatus,
  'method' : PayoutMethod,
  'userId' : UserId,
  'ticketId' : TicketId,
  'claimedAt' : Timestamp,
  'amountClaimed' : IDL.Nat,
});
export const UserPublic = IDL.Record({
  'id' : UserId,
  'country' : IDL.Text,
  'isGuest' : IDL.Bool,
  'name' : IDL.Text,
  'joinedAt' : Timestamp,
  'email' : IDL.Opt(IDL.Text),
  'currency' : IDL.Text,
});
export const LotteryId = IDL.Text;
export const DrawId = IDL.Text;
export const DrawStatus = IDL.Variant({
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
  'Upcoming' : IDL.Null,
});
export const Draw = IDL.Record({
  'id' : DrawId,
  'status' : DrawStatus,
  'drawnNumbers' : IDL.Vec(IDL.Nat),
  'fairnessSeal' : IDL.Text,
  'lotteryId' : LotteryId,
  'drawnAt' : IDL.Opt(Timestamp),
});
export const LotteryType = IDL.Variant({
  'NoLoss' : IDL.Null,
  'Classic645' : IDL.Null,
  'Daily' : IDL.Null,
  'NFTRaffle' : IDL.Null,
});
export const Lottery = IDL.Record({
  'id' : LotteryId,
  'lotteryType' : LotteryType,
  'name' : IDL.Text,
  'drawDate' : Timestamp,
  'isActive' : IDL.Bool,
  'participatingCountries' : IDL.Vec(IDL.Text),
  'ticketPrice' : IDL.Nat,
  'prizePool' : IDL.Nat,
});
export const BadgeType = IDL.Variant({
  'Gifter' : IDL.Null,
  'MegaWinner' : IDL.Null,
  'Participant' : IDL.Null,
  'Winner' : IDL.Null,
});
export const Badge = IDL.Record({
  'id' : IDL.Text,
  'badgeType' : BadgeType,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'earnedAt' : Timestamp,
});
export const TicketStatus = IDL.Variant({
  'Unclaimed' : IDL.Null,
  'Lost' : IDL.Null,
  'Active' : IDL.Null,
  'Winner' : IDL.Null,
  'InDraw' : IDL.Null,
});
export const Ticket = IDL.Record({
  'id' : TicketId,
  'status' : TicketStatus,
  'ownerId' : UserId,
  'isGifted' : IDL.Bool,
  'artSeed' : IDL.Nat,
  'lotteryId' : LotteryId,
  'purchasedAt' : Timestamp,
  'numbers' : IDL.Vec(IDL.Nat),
  'giftedTo' : IDL.Opt(IDL.Text),
});
export const StoreId = IDL.Text;
export const POSSale = IDL.Record({
  'id' : IDL.Text,
  'soldAt' : Timestamp,
  'storeId' : StoreId,
  'ticketIds' : IDL.Vec(TicketId),
  'commission' : IDL.Nat,
  'totalAmount' : IDL.Nat,
});
export const Store = IDL.Record({
  'id' : StoreId,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'hoursOpen' : IDL.Text,
  'address' : IDL.Text,
  'hasTickets' : IDL.Bool,
  'phone' : IDL.Opt(IDL.Text),
});
export const UserStats = IDL.Record({
  'badges' : IDL.Vec(IDL.Text),
  'totalWins' : IDL.Nat,
  'totalWon' : IDL.Nat,
  'totalSpent' : IDL.Nat,
  'totalTickets' : IDL.Nat,
});
export const Winner = IDL.Record({
  'id' : IDL.Text,
  'lotteryName' : IDL.Text,
  'country' : IDL.Text,
  'consentToShare' : IDL.Bool,
  'displayName' : IDL.Text,
  'prizeAmount' : IDL.Nat,
  'userId' : UserId,
  'wonAt' : Timestamp,
});
export const UserSettings = IDL.Record({
  'notificationsEnabled' : IDL.Bool,
  'country' : IDL.Text,
  'language' : IDL.Text,
  'currency' : IDL.Text,
});

export const idlService = IDL.Service({
  'claimPrize' : IDL.Func([TicketId, PayoutMethod], [IDL.Opt(PrizeClaim)], []),
  'createUser' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Bool],
      [UserPublic],
      [],
    ),
  'getDrawByLottery' : IDL.Func([LotteryId], [IDL.Vec(Draw)], ['query']),
  'getLatestDraw' : IDL.Func([LotteryId], [IDL.Opt(Draw)], ['query']),
  'getLotteries' : IDL.Func([], [IDL.Vec(Lottery)], ['query']),
  'getLotteryById' : IDL.Func([LotteryId], [IDL.Opt(Lottery)], ['query']),
  'getMyBadges' : IDL.Func([], [IDL.Vec(Badge)], ['query']),
  'getMyTickets' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
  'getStoreSales' : IDL.Func([StoreId], [IDL.Vec(POSSale)], ['query']),
  'getStores' : IDL.Func([], [IDL.Vec(Store)], ['query']),
  'getStoresByCountry' : IDL.Func([IDL.Text], [IDL.Vec(Store)], ['query']),
  'getTicketById' : IDL.Func([TicketId], [IDL.Opt(Ticket)], ['query']),
  'getUser' : IDL.Func([UserId], [IDL.Opt(UserPublic)], ['query']),
  'getUserStats' : IDL.Func([], [IDL.Opt(UserStats)], ['query']),
  'getWinners' : IDL.Func([], [IDL.Vec(Winner)], ['query']),
  'giftTicket' : IDL.Func([TicketId, IDL.Text], [IDL.Bool], []),
  'purchaseTicket' : IDL.Func(
      [LotteryId, IDL.Vec(IDL.Nat), IDL.Nat],
      [Ticket],
      [],
    ),
  'recordSale' : IDL.Func(
      [StoreId, IDL.Vec(TicketId), IDL.Nat, IDL.Nat],
      [POSSale],
      [],
    ),
  'updateSettings' : IDL.Func([UserSettings], [IDL.Bool], []),
  'updateUserProfile' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TicketId = IDL.Text;
  const PayoutMethod = IDL.Variant({
    'BankTransfer' : IDL.Null,
    'Crypto' : IDL.Null,
    'Wallet' : IDL.Null,
    'StoreCredit' : IDL.Null,
  });
  const ClaimStatus = IDL.Variant({
    'Processing' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const PrizeClaim = IDL.Record({
    'id' : IDL.Text,
    'status' : ClaimStatus,
    'method' : PayoutMethod,
    'userId' : UserId,
    'ticketId' : TicketId,
    'claimedAt' : Timestamp,
    'amountClaimed' : IDL.Nat,
  });
  const UserPublic = IDL.Record({
    'id' : UserId,
    'country' : IDL.Text,
    'isGuest' : IDL.Bool,
    'name' : IDL.Text,
    'joinedAt' : Timestamp,
    'email' : IDL.Opt(IDL.Text),
    'currency' : IDL.Text,
  });
  const LotteryId = IDL.Text;
  const DrawId = IDL.Text;
  const DrawStatus = IDL.Variant({
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
    'Upcoming' : IDL.Null,
  });
  const Draw = IDL.Record({
    'id' : DrawId,
    'status' : DrawStatus,
    'drawnNumbers' : IDL.Vec(IDL.Nat),
    'fairnessSeal' : IDL.Text,
    'lotteryId' : LotteryId,
    'drawnAt' : IDL.Opt(Timestamp),
  });
  const LotteryType = IDL.Variant({
    'NoLoss' : IDL.Null,
    'Classic645' : IDL.Null,
    'Daily' : IDL.Null,
    'NFTRaffle' : IDL.Null,
  });
  const Lottery = IDL.Record({
    'id' : LotteryId,
    'lotteryType' : LotteryType,
    'name' : IDL.Text,
    'drawDate' : Timestamp,
    'isActive' : IDL.Bool,
    'participatingCountries' : IDL.Vec(IDL.Text),
    'ticketPrice' : IDL.Nat,
    'prizePool' : IDL.Nat,
  });
  const BadgeType = IDL.Variant({
    'Gifter' : IDL.Null,
    'MegaWinner' : IDL.Null,
    'Participant' : IDL.Null,
    'Winner' : IDL.Null,
  });
  const Badge = IDL.Record({
    'id' : IDL.Text,
    'badgeType' : BadgeType,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'earnedAt' : Timestamp,
  });
  const TicketStatus = IDL.Variant({
    'Unclaimed' : IDL.Null,
    'Lost' : IDL.Null,
    'Active' : IDL.Null,
    'Winner' : IDL.Null,
    'InDraw' : IDL.Null,
  });
  const Ticket = IDL.Record({
    'id' : TicketId,
    'status' : TicketStatus,
    'ownerId' : UserId,
    'isGifted' : IDL.Bool,
    'artSeed' : IDL.Nat,
    'lotteryId' : LotteryId,
    'purchasedAt' : Timestamp,
    'numbers' : IDL.Vec(IDL.Nat),
    'giftedTo' : IDL.Opt(IDL.Text),
  });
  const StoreId = IDL.Text;
  const POSSale = IDL.Record({
    'id' : IDL.Text,
    'soldAt' : Timestamp,
    'storeId' : StoreId,
    'ticketIds' : IDL.Vec(TicketId),
    'commission' : IDL.Nat,
    'totalAmount' : IDL.Nat,
  });
  const Store = IDL.Record({
    'id' : StoreId,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'hoursOpen' : IDL.Text,
    'address' : IDL.Text,
    'hasTickets' : IDL.Bool,
    'phone' : IDL.Opt(IDL.Text),
  });
  const UserStats = IDL.Record({
    'badges' : IDL.Vec(IDL.Text),
    'totalWins' : IDL.Nat,
    'totalWon' : IDL.Nat,
    'totalSpent' : IDL.Nat,
    'totalTickets' : IDL.Nat,
  });
  const Winner = IDL.Record({
    'id' : IDL.Text,
    'lotteryName' : IDL.Text,
    'country' : IDL.Text,
    'consentToShare' : IDL.Bool,
    'displayName' : IDL.Text,
    'prizeAmount' : IDL.Nat,
    'userId' : UserId,
    'wonAt' : Timestamp,
  });
  const UserSettings = IDL.Record({
    'notificationsEnabled' : IDL.Bool,
    'country' : IDL.Text,
    'language' : IDL.Text,
    'currency' : IDL.Text,
  });
  
  return IDL.Service({
    'claimPrize' : IDL.Func(
        [TicketId, PayoutMethod],
        [IDL.Opt(PrizeClaim)],
        [],
      ),
    'createUser' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Bool],
        [UserPublic],
        [],
      ),
    'getDrawByLottery' : IDL.Func([LotteryId], [IDL.Vec(Draw)], ['query']),
    'getLatestDraw' : IDL.Func([LotteryId], [IDL.Opt(Draw)], ['query']),
    'getLotteries' : IDL.Func([], [IDL.Vec(Lottery)], ['query']),
    'getLotteryById' : IDL.Func([LotteryId], [IDL.Opt(Lottery)], ['query']),
    'getMyBadges' : IDL.Func([], [IDL.Vec(Badge)], ['query']),
    'getMyTickets' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
    'getStoreSales' : IDL.Func([StoreId], [IDL.Vec(POSSale)], ['query']),
    'getStores' : IDL.Func([], [IDL.Vec(Store)], ['query']),
    'getStoresByCountry' : IDL.Func([IDL.Text], [IDL.Vec(Store)], ['query']),
    'getTicketById' : IDL.Func([TicketId], [IDL.Opt(Ticket)], ['query']),
    'getUser' : IDL.Func([UserId], [IDL.Opt(UserPublic)], ['query']),
    'getUserStats' : IDL.Func([], [IDL.Opt(UserStats)], ['query']),
    'getWinners' : IDL.Func([], [IDL.Vec(Winner)], ['query']),
    'giftTicket' : IDL.Func([TicketId, IDL.Text], [IDL.Bool], []),
    'purchaseTicket' : IDL.Func(
        [LotteryId, IDL.Vec(IDL.Nat), IDL.Nat],
        [Ticket],
        [],
      ),
    'recordSale' : IDL.Func(
        [StoreId, IDL.Vec(TicketId), IDL.Nat, IDL.Nat],
        [POSSale],
        [],
      ),
    'updateSettings' : IDL.Func([UserSettings], [IDL.Bool], []),
    'updateUserProfile' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };