/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface POSSale {
    id: string;
    soldAt: Timestamp;
    storeId: StoreId;
    ticketIds: Array<TicketId>;
    commission: bigint;
    totalAmount: bigint;
}
export interface UserPublic {
    id: UserId;
    country: string;
    isGuest: boolean;
    name: string;
    joinedAt: Timestamp;
    email?: string;
    currency: string;
}
export interface Lottery {
    id: LotteryId;
    lotteryType: LotteryType;
    name: string;
    drawDate: Timestamp;
    isActive: boolean;
    participatingCountries: Array<string>;
    ticketPrice: bigint;
    prizePool: bigint;
}
export interface Draw {
    id: DrawId;
    status: DrawStatus;
    drawnNumbers: Array<bigint>;
    fairnessSeal: string;
    lotteryId: LotteryId;
    drawnAt?: Timestamp;
}
export type DrawId = string;
export type LotteryId = string;
export type TicketId = string;
export interface Badge {
    id: string;
    badgeType: BadgeType;
    name: string;
    description: string;
    earnedAt: Timestamp;
}
export type UserId = Principal;
export type StoreId = string;
export interface Winner {
    id: string;
    lotteryName: string;
    country: string;
    consentToShare: boolean;
    displayName: string;
    prizeAmount: bigint;
    userId: UserId;
    wonAt: Timestamp;
}
export interface UserSettings {
    notificationsEnabled: boolean;
    country: string;
    language: string;
    currency: string;
}
export interface Ticket {
    id: TicketId;
    status: TicketStatus;
    ownerId: UserId;
    isGifted: boolean;
    artSeed: bigint;
    lotteryId: LotteryId;
    purchasedAt: Timestamp;
    numbers: Array<bigint>;
    giftedTo?: string;
}
export interface PrizeClaim {
    id: string;
    status: ClaimStatus;
    method: PayoutMethod;
    userId: UserId;
    ticketId: TicketId;
    claimedAt: Timestamp;
    amountClaimed: bigint;
}
export interface Store {
    id: StoreId;
    lat: number;
    lng: number;
    country: string;
    city: string;
    name: string;
    hoursOpen: string;
    address: string;
    hasTickets: boolean;
    phone?: string;
}
export interface UserStats {
    badges: Array<string>;
    totalWins: bigint;
    totalWon: bigint;
    totalSpent: bigint;
    totalTickets: bigint;
}
export enum BadgeType {
    Gifter = "Gifter",
    MegaWinner = "MegaWinner",
    Participant = "Participant",
    Winner = "Winner"
}
export enum ClaimStatus {
    Processing = "Processing",
    Completed = "Completed",
    Pending = "Pending"
}
export enum DrawStatus {
    InProgress = "InProgress",
    Completed = "Completed",
    Upcoming = "Upcoming"
}
export enum LotteryType {
    NoLoss = "NoLoss",
    Classic645 = "Classic645",
    Daily = "Daily",
    NFTRaffle = "NFTRaffle"
}
export enum PayoutMethod {
    BankTransfer = "BankTransfer",
    Crypto = "Crypto",
    Wallet = "Wallet",
    StoreCredit = "StoreCredit"
}
export enum TicketStatus {
    Unclaimed = "Unclaimed",
    Lost = "Lost",
    Active = "Active",
    Winner = "Winner",
    InDraw = "InDraw"
}
export interface backendInterface {
    claimPrize(ticketId: TicketId, method: PayoutMethod): Promise<PrizeClaim | null>;
    createUser(name: string, email: string | null, country: string, currency: string, isGuest: boolean): Promise<UserPublic>;
    getDrawByLottery(lotteryId: LotteryId): Promise<Array<Draw>>;
    getLatestDraw(lotteryId: LotteryId): Promise<Draw | null>;
    getLotteries(): Promise<Array<Lottery>>;
    getLotteryById(id: LotteryId): Promise<Lottery | null>;
    getMyBadges(): Promise<Array<Badge>>;
    getMyTickets(): Promise<Array<Ticket>>;
    getStoreSales(storeId: StoreId): Promise<Array<POSSale>>;
    getStores(): Promise<Array<Store>>;
    getStoresByCountry(country: string): Promise<Array<Store>>;
    getTicketById(id: TicketId): Promise<Ticket | null>;
    getUser(id: UserId): Promise<UserPublic | null>;
    getUserStats(): Promise<UserStats | null>;
    getWinners(): Promise<Array<Winner>>;
    giftTicket(ticketId: TicketId, recipientIdentifier: string): Promise<boolean>;
    purchaseTicket(lotteryId: LotteryId, numbers: Array<bigint>, artSeed: bigint): Promise<Ticket>;
    recordSale(storeId: StoreId, ticketIds: Array<TicketId>, totalAmount: bigint, commission: bigint): Promise<POSSale>;
    updateSettings(settings: UserSettings): Promise<boolean>;
    updateUserProfile(name: string | null, email: string | null, country: string | null, currency: string | null): Promise<boolean>;
}
import type { Badge as _Badge, BadgeType as _BadgeType, ClaimStatus as _ClaimStatus, Draw as _Draw, DrawId as _DrawId, DrawStatus as _DrawStatus, Lottery as _Lottery, LotteryId as _LotteryId, LotteryType as _LotteryType, PayoutMethod as _PayoutMethod, PrizeClaim as _PrizeClaim, Store as _Store, StoreId as _StoreId, Ticket as _Ticket, TicketId as _TicketId, TicketStatus as _TicketStatus, Timestamp as _Timestamp, UserId as _UserId, UserPublic as _UserPublic, UserStats as _UserStats } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async claimPrize(arg0: TicketId, arg1: PayoutMethod): Promise<PrizeClaim | null> {
        if (this.processError) {
            try {
                const result = await this.actor.claimPrize(arg0, to_candid_PayoutMethod_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimPrize(arg0, to_candid_PayoutMethod_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createUser(arg0: string, arg1: string | null, arg2: string, arg3: string, arg4: boolean): Promise<UserPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return from_candid_UserPublic_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return from_candid_UserPublic_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDrawByLottery(arg0: LotteryId): Promise<Array<Draw>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDrawByLottery(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDrawByLottery(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestDraw(arg0: LotteryId): Promise<Draw | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestDraw(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestDraw(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLotteries(): Promise<Array<Lottery>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLotteries();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLotteries();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLotteryById(arg0: LotteryId): Promise<Lottery | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLotteryById(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLotteryById(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBadges(): Promise<Array<Badge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBadges();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBadges();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTickets(): Promise<Array<Ticket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTickets();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTickets();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStoreSales(arg0: StoreId): Promise<Array<POSSale>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoreSales(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoreSales(arg0);
            return result;
        }
    }
    async getStores(): Promise<Array<Store>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStores();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStores();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStoresByCountry(arg0: string): Promise<Array<Store>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoresByCountry(arg0);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoresByCountry(arg0);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTicketById(arg0: TicketId): Promise<Ticket | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTicketById(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTicketById(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: UserId): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserStats(): Promise<UserStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserStats();
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserStats();
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWinners(): Promise<Array<Winner>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWinners();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWinners();
            return result;
        }
    }
    async giftTicket(arg0: TicketId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.giftTicket(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.giftTicket(arg0, arg1);
            return result;
        }
    }
    async purchaseTicket(arg0: LotteryId, arg1: Array<bigint>, arg2: bigint): Promise<Ticket> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseTicket(arg0, arg1, arg2);
                return from_candid_Ticket_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseTicket(arg0, arg1, arg2);
            return from_candid_Ticket_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordSale(arg0: StoreId, arg1: Array<TicketId>, arg2: bigint, arg3: bigint): Promise<POSSale> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSale(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSale(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateSettings(arg0: UserSettings): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0);
            return result;
        }
    }
    async updateUserProfile(arg0: string | null, arg1: string | null, arg2: string | null, arg3: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_BadgeType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BadgeType): BadgeType {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Badge_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Badge): Badge {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_ClaimStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClaimStatus): ClaimStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_DrawStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DrawStatus): DrawStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Draw_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Draw): Draw {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_LotteryType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LotteryType): LotteryType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Lottery_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lottery): Lottery {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_PayoutMethod_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PayoutMethod): PayoutMethod {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_PrizeClaim_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrizeClaim): PrizeClaim {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Store_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Store): Store {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_TicketStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TicketStatus): TicketStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Ticket_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ticket): Ticket {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserPublic_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPublic): UserPublic {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Draw]): Draw | null {
    return value.length === 0 ? null : from_candid_Draw_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Lottery]): Lottery | null {
    return value.length === 0 ? null : from_candid_Lottery_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PrizeClaim]): PrizeClaim | null {
    return value.length === 0 ? null : from_candid_PrizeClaim_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Ticket]): Ticket | null {
    return value.length === 0 ? null : from_candid_Ticket_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPublic]): UserPublic | null {
    return value.length === 0 ? null : from_candid_UserPublic_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserStats]): UserStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    country: string;
    isGuest: boolean;
    name: string;
    joinedAt: _Timestamp;
    email: [] | [string];
    currency: string;
}): {
    id: UserId;
    country: string;
    isGuest: boolean;
    name: string;
    joinedAt: Timestamp;
    email?: string;
    currency: string;
} {
    return {
        id: value.id,
        country: value.country,
        isGuest: value.isGuest,
        name: value.name,
        joinedAt: value.joinedAt,
        email: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.email)),
        currency: value.currency
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DrawId;
    status: _DrawStatus;
    drawnNumbers: Array<bigint>;
    fairnessSeal: string;
    lotteryId: _LotteryId;
    drawnAt: [] | [_Timestamp];
}): {
    id: DrawId;
    status: DrawStatus;
    drawnNumbers: Array<bigint>;
    fairnessSeal: string;
    lotteryId: LotteryId;
    drawnAt?: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_DrawStatus_n17(_uploadFile, _downloadFile, value.status),
        drawnNumbers: value.drawnNumbers,
        fairnessSeal: value.fairnessSeal,
        lotteryId: value.lotteryId,
        drawnAt: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.drawnAt))
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LotteryId;
    lotteryType: _LotteryType;
    name: string;
    drawDate: _Timestamp;
    isActive: boolean;
    participatingCountries: Array<string>;
    ticketPrice: bigint;
    prizePool: bigint;
}): {
    id: LotteryId;
    lotteryType: LotteryType;
    name: string;
    drawDate: Timestamp;
    isActive: boolean;
    participatingCountries: Array<string>;
    ticketPrice: bigint;
    prizePool: bigint;
} {
    return {
        id: value.id,
        lotteryType: from_candid_LotteryType_n24(_uploadFile, _downloadFile, value.lotteryType),
        name: value.name,
        drawDate: value.drawDate,
        isActive: value.isActive,
        participatingCountries: value.participatingCountries,
        ticketPrice: value.ticketPrice,
        prizePool: value.prizePool
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    badgeType: _BadgeType;
    name: string;
    description: string;
    earnedAt: _Timestamp;
}): {
    id: string;
    badgeType: BadgeType;
    name: string;
    description: string;
    earnedAt: Timestamp;
} {
    return {
        id: value.id,
        badgeType: from_candid_BadgeType_n30(_uploadFile, _downloadFile, value.badgeType),
        name: value.name,
        description: value.description,
        earnedAt: value.earnedAt
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TicketId;
    status: _TicketStatus;
    ownerId: _UserId;
    isGifted: boolean;
    artSeed: bigint;
    lotteryId: _LotteryId;
    purchasedAt: _Timestamp;
    numbers: Array<bigint>;
    giftedTo: [] | [string];
}): {
    id: TicketId;
    status: TicketStatus;
    ownerId: UserId;
    isGifted: boolean;
    artSeed: bigint;
    lotteryId: LotteryId;
    purchasedAt: Timestamp;
    numbers: Array<bigint>;
    giftedTo?: string;
} {
    return {
        id: value.id,
        status: from_candid_TicketStatus_n35(_uploadFile, _downloadFile, value.status),
        ownerId: value.ownerId,
        isGifted: value.isGifted,
        artSeed: value.artSeed,
        lotteryId: value.lotteryId,
        purchasedAt: value.purchasedAt,
        numbers: value.numbers,
        giftedTo: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.giftedTo))
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _StoreId;
    lat: number;
    lng: number;
    country: string;
    city: string;
    name: string;
    hoursOpen: string;
    address: string;
    hasTickets: boolean;
    phone: [] | [string];
}): {
    id: StoreId;
    lat: number;
    lng: number;
    country: string;
    city: string;
    name: string;
    hoursOpen: string;
    address: string;
    hasTickets: boolean;
    phone?: string;
} {
    return {
        id: value.id,
        lat: value.lat,
        lng: value.lng,
        country: value.country,
        city: value.city,
        name: value.name,
        hoursOpen: value.hoursOpen,
        address: value.address,
        hasTickets: value.hasTickets,
        phone: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ClaimStatus;
    method: _PayoutMethod;
    userId: _UserId;
    ticketId: _TicketId;
    claimedAt: _Timestamp;
    amountClaimed: bigint;
}): {
    id: string;
    status: ClaimStatus;
    method: PayoutMethod;
    userId: UserId;
    ticketId: TicketId;
    claimedAt: Timestamp;
    amountClaimed: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ClaimStatus_n6(_uploadFile, _downloadFile, value.status),
        method: from_candid_PayoutMethod_n8(_uploadFile, _downloadFile, value.method),
        userId: value.userId,
        ticketId: value.ticketId,
        claimedAt: value.claimedAt,
        amountClaimed: value.amountClaimed
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    InProgress: null;
} | {
    Completed: null;
} | {
    Upcoming: null;
}): DrawStatus {
    return "InProgress" in value ? DrawStatus.InProgress : "Completed" in value ? DrawStatus.Completed : "Upcoming" in value ? DrawStatus.Upcoming : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    NoLoss: null;
} | {
    Classic645: null;
} | {
    Daily: null;
} | {
    NFTRaffle: null;
}): LotteryType {
    return "NoLoss" in value ? LotteryType.NoLoss : "Classic645" in value ? LotteryType.Classic645 : "Daily" in value ? LotteryType.Daily : "NFTRaffle" in value ? LotteryType.NFTRaffle : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Gifter: null;
} | {
    MegaWinner: null;
} | {
    Participant: null;
} | {
    Winner: null;
}): BadgeType {
    return "Gifter" in value ? BadgeType.Gifter : "MegaWinner" in value ? BadgeType.MegaWinner : "Participant" in value ? BadgeType.Participant : "Winner" in value ? BadgeType.Winner : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Unclaimed: null;
} | {
    Lost: null;
} | {
    Active: null;
} | {
    Winner: null;
} | {
    InDraw: null;
}): TicketStatus {
    return "Unclaimed" in value ? TicketStatus.Unclaimed : "Lost" in value ? TicketStatus.Lost : "Active" in value ? TicketStatus.Active : "Winner" in value ? TicketStatus.Winner : "InDraw" in value ? TicketStatus.InDraw : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Processing: null;
} | {
    Completed: null;
} | {
    Pending: null;
}): ClaimStatus {
    return "Processing" in value ? ClaimStatus.Processing : "Completed" in value ? ClaimStatus.Completed : "Pending" in value ? ClaimStatus.Pending : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    BankTransfer: null;
} | {
    Crypto: null;
} | {
    Wallet: null;
} | {
    StoreCredit: null;
}): PayoutMethod {
    return "BankTransfer" in value ? PayoutMethod.BankTransfer : "Crypto" in value ? PayoutMethod.Crypto : "Wallet" in value ? PayoutMethod.Wallet : "StoreCredit" in value ? PayoutMethod.StoreCredit : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Draw>): Array<Draw> {
    return value.map((x)=>from_candid_Draw_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lottery>): Array<Lottery> {
    return value.map((x)=>from_candid_Lottery_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Badge>): Array<Badge> {
    return value.map((x)=>from_candid_Badge_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ticket>): Array<Ticket> {
    return value.map((x)=>from_candid_Ticket_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Store>): Array<Store> {
    return value.map((x)=>from_candid_Store_n38(_uploadFile, _downloadFile, x));
}
function to_candid_PayoutMethod_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PayoutMethod): _PayoutMethod {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PayoutMethod): {
    BankTransfer: null;
} | {
    Crypto: null;
} | {
    Wallet: null;
} | {
    StoreCredit: null;
} {
    return value == PayoutMethod.BankTransfer ? {
        BankTransfer: null
    } : value == PayoutMethod.Crypto ? {
        Crypto: null
    } : value == PayoutMethod.Wallet ? {
        Wallet: null
    } : value == PayoutMethod.StoreCredit ? {
        StoreCredit: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
